### ISSUE TITLE
certification expired on site

### ISSUE THREAD

**Issue by MichaelLSmith** [Tycholiz/modal-interchange-chart#12]
Hi Kyle,

This is such a great app for musicians. I've totally come to depend on it. When I visit it now, chrome spits out a message saying that's it not secure anymore. Maybe the certification expired? Anyway, where are you hosting this? Do you need any help hosting it and maintaining it? I'd be happy to pitch in a bit.

**Comment by Tycholiz** [comment]
Hey @MichaelLSmith my deepest apologies for the late response!!

Yes I have not been aware of this, thanks for bringing it to my attention! I think I will just need to renew the domain.

Thanks for your kind words and support!!

**Comment by Tycholiz** [comment]
Yes it was a domain expired issue. I just renewed it, so hopefully it comes back on its own soon enough. I will monitor this to make sure we are good to go..

Thanks again for bringing this to my attention!

**Comment by Tycholiz** [comment]
@MichaelLSmith do you have any bandwidth to help on this? DNS is not my strong-suit

Not sure what steps need to be taken, to get the site back up

**Comment by Tycholiz** [comment]
Hey @MichaelLSmith thanks for your patience,

The site is back up now, closing!
